# Site settings
title_left    : ""
title_right   : "My Random Notes" # default ""
description   : "My personal blog to share random stuff!"
keywords      : "Jekyll, theme, free, download, SEO, blog, web, minimalist, thinkspace"
url           : https://myrandomnotes.com/ # site url
baseurl       : "" # apply repo name like "/myproject" if used under gh-pages branch, else (under master branch) just leave empty/blank
cover         : "" # image uri like logo/cover image for site seo

google_analytics  : UA-XXXXX-XX
twitter_username  : "akhil_baburaj"
github_username   : "akhilbaburaj"
linkedin_username : "akhilbaburaj"
comments_enabled  : false # if enabled (set to true), please provide your disqus_username
disqus_shortname  : ""
postshare_enabled : false


# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source      : ./
destination : ./_site

# Category Configuration
defaults:
  -
    scope:
      path: "_posts/stories"
    values:
        permalink: /stories/:year/:title/
        categories: ['Stories']
  -
    scope:
      path: "_posts/photos"
    values:
        permalink: /stories/:year/:title/
        categories: ['Photos']
  -
    scope:
      path: "_posts/tech"
    values:
        permalink: /stories/:year/:title/
        categories: ['Tech']         

# Sass configuration
sass:
  sass_dir  : assets/scss
  style     : compressed # expanded

# Author settings
author:
  name     : "Akhil Baburaj"

plugins:
  - jekyll-sitemap
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md", "script"]
